trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

stages:
  - stage: Validate
    displayName: Validate terraform
    variables:
      - template: .azuredevops/v1/variables/environments/shared.yml
    jobs:
      - job: ValidateCode
        displayName: Validate code
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            fetchDepth: 0

          - template: /.azuredevops/v1/templates/opentofu_install.yml

          # - publish: ${{ variables.pythonSrcDirectory }}
          #   displayName: Publish artifact module
          #   artifact: module
