backend:
  path: terraform.tfstate

provider:
  azurerm:
    tenant_id: ${AZURE_TENANT_ID}
    subscription_id: ${AZURE_SUBSCRIPTION_ID}
    client_id: ${AZURE_CLIENT_ID}
    client_secret: ${AZURE_CLIENT_SECRET}

constructs:
  resource_group_secure:
    name: rg-datalake
    location: westeurope
    sequence_number: "001"
    management_lock:
      lock_level: CanNotDelete
      notes: "Resource group for data lake storage accounts"

  data_lake:
    source_storage:
      storage:
        name: stgsource
        location: westeurope
        sequence_number: "001"
        account_replication_type: LRS
        account_tier: Standard
        account_kind: StorageV2
        is_hns_enabled: true
        containers:
          - name: raw

    bronze_storage:
      storage:
        name: stgbronze
        location: westeurope
        sequence_number: "001"
        account_replication_type: LRS
        account_tier: Standard
        account_kind: StorageV2
        is_hns_enabled: true
        containers:
          - name: processed

    silver_storage:
      storage:
        name: stgsilver
        location: westeurope
        sequence_number: "001"
        account_replication_type: LRS
        account_tier: Standard
        account_kind: StorageV2
        is_hns_enabled: true
        containers:
          - name: curated

    gold_storage:
      storage:
        name: stggold
        location: westeurope
        sequence_number: "001"
        account_replication_type: LRS
        account_tier: Standard
        account_kind: StorageV2
        is_hns_enabled: true
        containers:
          - name: aggregated
